#!/usr/bin/env bash
# Single-task online RL for task_16_email_triage
# Reward = task16 event shaping v2 + terminal reward only

set -euo pipefail

if [ -f "${HOME}/.pinchbench_env" ]; then
  set -a
  # shellcheck disable=SC1090
  source "${HOME}/.pinchbench_env"
  set +a
fi

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TASK16_DATA_DIR="${TASK16_DATA_DIR:-${REPO_ROOT}/rl/data/prompts_task16_variants}"
mkdir -p "${TASK16_DATA_DIR}"
TRAIN_LOG_PATH="${TRAIN_LOG_PATH:-/workspace/pinchbench-skill/task16_event_only_v2_rl.log}"

export HF_HUB_ENABLE_HF_TRANSFER=0
export HUGGINGFACE_HUB_ENABLE_HF_TRANSFER=0
export RAY_raylet_start_wait_time_s="${RAY_raylet_start_wait_time_s:-60}"

python3 "${REPO_ROOT}/rl/train/build_task16_variant_prompts.py" \
  --tasks-dir "${REPO_ROOT}/tasks" \
  --output-dir "${TASK16_DATA_DIR}" \
  --val-count "${TASK16_VAL_COUNT:-5}"

export VERL_MODEL="${VERL_MODEL:-Qwen/Qwen3-1.7B}"
export REWARD_MODE="${REWARD_MODE:-task16-event-only-v2}"
export PINCHBENCH_REWARD_MODULE_OVERRIDE="${PINCHBENCH_REWARD_MODULE_OVERRIDE:-${REPO_ROOT}/rl/agent_loop/task16_event_reward/reward_task16_event_only_v2.py}"
export DATA_DIR="${TASK16_DATA_DIR}"
export PINCHBENCH_DATA_DIR_OVERRIDE="${TASK16_DATA_DIR}"
export BATCH_SIZE="${BATCH_SIZE:-1}"
export MICRO_BATCH="${MICRO_BATCH:-1}"
export TOTAL_EPOCHS="${TOTAL_EPOCHS:-4}"
export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-32}"
export TEST_FREQ="${TEST_FREQ:-4}"
export SAVE_FREQ="${SAVE_FREQ:-4}"
export PINCHBENCH_REWARD_RETURN_MODE="${PINCHBENCH_REWARD_RETURN_MODE:-turn}"
export PINCHBENCH_REWARD_ASSIGNMENT="${PINCHBENCH_REWARD_ASSIGNMENT:-turn_broadcast}"
export PINCHBENCH_NO_MASKED_WHITEN="${PINCHBENCH_NO_MASKED_WHITEN:-1}"
export PINCHBENCH_TASK16_TERMINAL_REWARD_WEIGHT="${PINCHBENCH_TASK16_TERMINAL_REWARD_WEIGHT:-0.8}"
export PINCHBENCH_TASK_EMA_INIT="${PINCHBENCH_TASK_EMA_INIT:-0.0}"
export PINCHBENCH_TASK_EMA_ALPHA="${PINCHBENCH_TASK_EMA_ALPHA:-0.05}"
export PINCHBENCH_TASK_EMA_VAR_INIT="${PINCHBENCH_TASK_EMA_VAR_INIT:-0.0}"
export ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-0.8}"
export VAL_DO_SAMPLE="${VAL_DO_SAMPLE:-False}"
export VAL_TEMPERATURE="${VAL_TEMPERATURE:-1.0}"
export VAL_TOP_P="${VAL_TOP_P:-1.0}"
export VAL_TOP_K="${VAL_TOP_K:--1}"
export VAL_N="${VAL_N:-1}"
export MAX_TURNS="${MAX_TURNS:-8}"
export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-16000}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-4096}"
export VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-32768}"
export VLLM_GPU_MEM_UTIL="${VLLM_GPU_MEM_UTIL:-0.22}"
export VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS:-8}"
export ROLLOUT_LAYERED_SUMMON="${ROLLOUT_LAYERED_SUMMON:-False}"
export RUN_VERSION="${RUN_VERSION:-task16_event_only_v2_qwen31}"
export OPENCLAW_HOST="${OPENCLAW_HOST:-8.163.82.224}"
export OPENCLAW_PORT="${OPENCLAW_PORT:-22}"
export OPENCLAW_USER="${OPENCLAW_USER:-root}"
export ECS_HOST="${ECS_HOST:-${OPENCLAW_HOST}}"

echo "=============================="
echo "task_16 event-only RL v2"
echo "MODEL=${VERL_MODEL}"
echo "DATA_DIR=${DATA_DIR}"
echo "REWARD_MODE=${REWARD_MODE}"
echo "REWARD_OVERRIDE=${PINCHBENCH_REWARD_MODULE_OVERRIDE}"
echo "REWARD_ASSIGNMENT=${PINCHBENCH_REWARD_ASSIGNMENT}"
echo "NO_MASKED_WHITEN=${PINCHBENCH_NO_MASKED_WHITEN}"
echo "TASK16_TERMINAL_WEIGHT=${PINCHBENCH_TASK16_TERMINAL_REWARD_WEIGHT}"
echo "EMA_INIT=${PINCHBENCH_TASK_EMA_INIT} EMA_ALPHA=${PINCHBENCH_TASK_EMA_ALPHA} EMA_VAR_INIT=${PINCHBENCH_TASK_EMA_VAR_INIT}"
echo "ROLLOUT_TEMPERATURE=${ROLLOUT_TEMPERATURE}"
echo "VAL_DO_SAMPLE=${VAL_DO_SAMPLE} VAL_TEMPERATURE=${VAL_TEMPERATURE} VAL_TOP_P=${VAL_TOP_P} VAL_TOP_K=${VAL_TOP_K} VAL_N=${VAL_N}"
echo "TOTAL_EPOCHS=${TOTAL_EPOCHS} TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS}"
echo "ROLLOUT_LAYERED_SUMMON=${ROLLOUT_LAYERED_SUMMON}"
echo "OPENCLAW=${OPENCLAW_USER}@${OPENCLAW_HOST}:${OPENCLAW_PORT}"
echo "LOG=${TRAIN_LOG_PATH}"
echo "=============================="

DATA_DIR="${DATA_DIR}" \
PINCHBENCH_DATA_DIR_OVERRIDE="${PINCHBENCH_DATA_DIR_OVERRIDE}" \
VERL_MODEL="${VERL_MODEL}" \
REWARD_MODE="${REWARD_MODE}" \
PINCHBENCH_REWARD_MODULE_OVERRIDE="${PINCHBENCH_REWARD_MODULE_OVERRIDE}" \
PINCHBENCH_REWARD_RETURN_MODE="${PINCHBENCH_REWARD_RETURN_MODE}" \
PINCHBENCH_REWARD_ASSIGNMENT="${PINCHBENCH_REWARD_ASSIGNMENT}" \
PINCHBENCH_NO_MASKED_WHITEN="${PINCHBENCH_NO_MASKED_WHITEN}" \
PINCHBENCH_TERMINAL_REWARD_WEIGHT="${PINCHBENCH_TASK16_TERMINAL_REWARD_WEIGHT}" \
PINCHBENCH_TASK_EMA_INIT="${PINCHBENCH_TASK_EMA_INIT}" \
PINCHBENCH_TASK_EMA_ALPHA="${PINCHBENCH_TASK_EMA_ALPHA}" \
PINCHBENCH_TASK_EMA_VAR_INIT="${PINCHBENCH_TASK_EMA_VAR_INIT}" \
ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE}" \
VAL_DO_SAMPLE="${VAL_DO_SAMPLE}" \
VAL_TEMPERATURE="${VAL_TEMPERATURE}" \
VAL_TOP_P="${VAL_TOP_P}" \
VAL_TOP_K="${VAL_TOP_K}" \
VAL_N="${VAL_N}" \
BATCH_SIZE="${BATCH_SIZE}" \
MICRO_BATCH="${MICRO_BATCH}" \
TOTAL_EPOCHS="${TOTAL_EPOCHS}" \
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS}" \
TEST_FREQ="${TEST_FREQ}" \
SAVE_FREQ="${SAVE_FREQ}" \
MAX_TURNS="${MAX_TURNS}" \
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH}" \
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH}" \
VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN}" \
VLLM_GPU_MEM_UTIL="${VLLM_GPU_MEM_UTIL}" \
VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS}" \
ROLLOUT_LAYERED_SUMMON="${ROLLOUT_LAYERED_SUMMON}" \
RUN_VERSION="${RUN_VERSION}" \
OPENCLAW_HOST="${OPENCLAW_HOST}" \
OPENCLAW_PORT="${OPENCLAW_PORT}" \
OPENCLAW_USER="${OPENCLAW_USER}" \
bash "${REPO_ROOT}/rl/train/run_reinforce_lora.sh" | tee "${TRAIN_LOG_PATH}"
